// vue/vuejs/숫자야구/numberBaseball.vue
<template>
    <div>
        <h1>{{result}}</h1>
        <form v-on:submit.prevent="doSubmit">
            <input ref="answer" maxlength="4" v-model="value">
            <button type="submit">입력</button>
        </form>
        <div>시도 : {{tries.length}}</div>
        <ul>
            <li v-for="t in tries" v-bind:key="t">
                <div>{{t.try}}</div>
                <div>{{t.result}}</div>
            </li>
        </ul>
    </div>
</template>

<script>
    const getNumber = ()=>{
        let candidates = [1,2,3,4,5,6,7,8,9];
        const array = [];
        for(let i=0; i<4; i ++){
            const choosen = candidates.splice(Math.floor(Math.random()*(9-i)),1)[0];
            array.push(choosen);
        }
        return array;
    }
    export default { // main.js 에서 import. numberBaseball 객체를 import할 수 있다.
        data(){
            return {
                answer: getNumber(),
                tries: [],
                value: "",
                result: "",
            }
        },
        methods: {
            doSubmit(e){
                if(this.value === this.answer.join("")){
                    this.tries.push({
                        try: this.value,
                        result: "홈런",
                    });
                    this.result = "홈런";
                    alert("홈런");
                    this.tries = [];
                } else {
                    let strike = 0;
                    let ball = 0;
                    const answerArray = this.value.split("").map(v=> parseInt(v));
                    for (let i=0; i<4; i++){
                        if(answerArray[i] === this.answer[i]){ // 숫자 자리수 모두 정답
                            strike++;
                        } else if(this.answer.includes(answerArray[i])){ // 숫자만 정답
                            ball++;
                        }
                    }
                    this.tries.push({
                        try: this.value,
                        result: `${strike} 스트라이크, ${ball} 볼 입니다.`
                    })
                    if(this.tries.length > 9){                         
                        this.result =  `실패!!`;
                        alert(`답= ${this.answer.join(',')}`);
                        this.answer = getNumber();
                        this.tries = [];
                        this.$refs.answer.focus();
                    }
                }
                this.value = "";
                this.$refs.answer.focus();
            }
        }
    };
</script>

<style>
</style>

// react-zero/7numberbaseball-hooks/NumberBaseball.jsx
import React, {memo} from 'react';
const {useState, useRef}  = React;

import Try from './Try';

function getNumbers(){
    const candidate = [1,2,3,4,5,6,7,8,9];
    const arr = [];
    for (let i=0; i < 4; i++) {
        const chosen = candidate.splice(Math.floor(Math.random() * (9 - i)), 1)[0];
        arr.push(chosen);
    }
    return arr;
}

const NumberBaseball = memo(() => {
    const [answer, setAnswer ] = useState(getNumbers());
    const [value, setValue ] = useState('');
    const [result, setResult ] = useState('');
    const [tries, setTries ] = useState([]);
    const inputRef = useRef(null);

    const onSubmitForm = (e) => {
        e.preventDefault();
        if (!value || tries.length >= 10) {
            return false;
        }

        if (value === answer.join('')) {
            setResult('홈런');
            setValue('');
            setTries((prevTries)=>{
                return [...prevTries, {try: value, result: '홈런'}]
            });
            resetGame('홈런');
        } else {
            const answerArray = value.split('').map(v => parseInt(v));
            let strike = 0;
            let ball = 0;
            if (tries.length >= 9) {
                setResult('실패');
                resetGame(`실패. 게임 다시 시작 ${answer.join('')}`);
            } else {
                for (let i=0; i<4; i++) {
                    if (answerArray[i] === answer[i]) {
                        strike += 1;
                    } else if (answer.includes(answerArray[i])) {
                        ball += 1;
                    }
                }
                setValue('');
                setTries((prevTries)=>{
                    return [...prevTries, {try: value, result: `${strike} 스트라이크, ${ball} 볼`}]
                });
            }
        }

        setValue('');
        inputRef.current.focus();
    };
    const resetGame = (word) => {
        alert(word);
        setValue('');
        setAnswer(getNumbers());
        setTries([]);
    };
    const onChangeInput = (e) => { 
        setValue(e.target.value);
    };

    return (
        <>
            <div>
                <form onSubmit={onSubmitForm}>
                    <input ref={inputRef} maxLength={4} type="text" value={value} onChange={onChangeInput}/>
                    <button type="submit">입력</button>
                </form>
                <div>시도 : {tries.length}</div>
                <div>
                    <Try tries={tries}></Try>
                </div>
            </div>
        </>
    );
    
});

export default NumberBaseball;
